# Generated by Django 4.1.6 on 2023-02-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(default='', verbose_name='Request')),
                ('response', models.TextField(default='', verbose_name='Response')),
                ('retry_times', models.IntegerField(default=0, verbose_name='Retry Times')),
                ('max_retries', models.IntegerField(default=10, verbose_name='Max Retries')),
                ('timeout', models.IntegerField(default=2, verbose_name='Timeout')),
                ('timeout_multiplier', models.IntegerField(default=2, verbose_name='Timeout Multiplier')),
                ('exception_name', models.CharField(choices=[('Pending', 'Pending'), ('Service Down', 'Service Down'), ('Service Error', 'Service Error'), ('Limit Error', 'Limit Error'), ('Insufficient Balance', 'Insufficient Balance')], max_length=100, verbose_name='Exception Name')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Opened', max_length=100, verbose_name='Transaction Status')),
                ('closed_reason', models.CharField(choices=[('Retry Reached', 'Retry Reached'), ('Still Open', 'Still Open'), ('Went Through', 'Went Through')], default='Still Open', max_length=100, verbose_name='Closed Reason')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
