# Generated by Django 4.1.1 on 2022-09-07 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='Gateway')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('transaction_object', models.TextField(blank=True, null=True)),
                ('refunded', models.BooleanField(default=False, verbose_name='Refunded')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Customer Email')),
                ('payment_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('Waiting Payment', 'Waiting Payment'), ('Cancelled', 'Cancelled'), ('Payment Success', 'Payment Success'), ('Payment Failed', 'Payment Failed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=50, verbose_name='Status')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
            ],
        ),
        migrations.CreateModel(
            name='ZesaTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Error Message')),
                ('agent_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agent Reference')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('recharge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recharge ID')),
                ('reply_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply Code')),
                ('reply_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply Message')),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wallet Balance')),
                ('meter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meter')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name')),
                ('tokens', models.TextField(blank=True, null=True, verbose_name='Tokens')),
                ('created_at', models.CharField(blank=True, default=django.utils.timezone.now, max_length=255, null=True, verbose_name='Created At')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kwikpay.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AirtimeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Error Message')),
                ('agent_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agent Reference')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final Balance')),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Initial Balance')),
                ('recharge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recharge ID')),
                ('reply_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply Code')),
                ('reply_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply Message')),
                ('sms', models.CharField(blank=True, max_length=255, null=True, verbose_name='SMS')),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wallet Balance')),
                ('window', models.CharField(blank=True, max_length=255, null=True, verbose_name='Window')),
                ('created_at', models.CharField(blank=True, default=django.utils.timezone.now, max_length=255, null=True, verbose_name='Created At')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kwikpay.transaction')),
            ],
        ),
    ]
