# Generated by Django 4.1.6 on 2023-02-03 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percent')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Bill', 'Bill')], max_length=50, verbose_name='Package Type')),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Package Price')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('get_offers', models.BooleanField(default=False, verbose_name='Get Offers')),
                ('get_newsletters', models.BooleanField(default=False, verbose_name='Get Newsletters')),
            ],
        ),
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('query', models.TextField(verbose_name='Query')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('updated_at', models.CharField(max_length=50, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtime_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Airtime Amount')),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bill Amount')),
                ('data_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Data Amount')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meter Number')),
                ('operator', models.CharField(max_length=50, verbose_name='Operator')),
                ('service', models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Electricity Bill', 'Electricity Bill')], max_length=50, verbose_name='Service')),
                ('fulfilled', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
